# Generated by Django 3.2.7 on 2022-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityservice',
            name='status',
            field=models.CharField(blank=True, choices=[('not started', 'not started'), ('wait', 'wait'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='not started', max_length=100, null=True),
        ),
    ]
