# Generated by Django 3.2.7 on 2022-04-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_cityservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
