# Generated by Django 3.2.9 on 2022-07-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_place_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_service', to='parsing.cityservice')),
            ],
            options={
                'verbose_name': 'Файл для хабов',
                'verbose_name_plural': 'Файлы для хабов',
            },
        ),
    ]
