# Generated by Django 3.2.9 on 2022-07-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_cityservicefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityservicefile',
            name='city_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='parsing.cityservice'),
        ),
    ]
